<div>
    <section class="border-b border-stone-200 bg-[#f6f3ed]">
        <div class="mx-auto max-w-7xl px-4 pb-8 pt-7 sm:px-6 sm:py-14 lg:px-8">
            <div class="flex items-center justify-between"><span class="inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.2em] text-cyan-800"><span class="size-2 rounded-full bg-cyan-500"></span>Live television directory</span><span class="text-xs font-semibold text-slate-400">Streams from listed providers</span></div>
            <div class="mt-7 grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 class="max-w-3xl text-[42px] font-extrabold leading-[.92] tracking-[-.055em] sm:text-6xl">Television without borders.</h1><p class="mt-5 max-w-2xl leading-7 text-slate-600">Explore news, culture, public broadcasting, and entertainment from around the world. Search the directory or begin with a country.</p></div><dl class="grid grid-cols-2 divide-x divide-stone-300 border-y border-stone-300 py-4 lg:min-w-80"><div class="pr-5"><dt class="text-[9px] font-extrabold uppercase tracking-wider text-slate-400">Channels</dt><dd class="mt-1 text-3xl font-extrabold">{{ number_format($channels->total()) }}</dd></div><div class="pl-5"><dt class="text-[9px] font-extrabold uppercase tracking-wider text-slate-400">Countries</dt><dd class="mt-1 text-3xl font-extrabold">{{ $countries->count() }}</dd></div></dl></div>

            <div x-data="{ open: false }">
                <button type="button" @click="open = !open" :aria-expanded="open" class="mt-7 flex w-full items-center justify-between rounded-2xl border border-stone-300 bg-white px-4 py-4 text-sm font-extrabold sm:hidden"><span>Search and filters</span><span x-text="open ? '−' : '+'"></span></button>
                <form wire:submit="applyFilters" :class="open ? 'grid' : 'hidden sm:grid'" class="mt-3 gap-2 rounded-2xl border border-stone-300 bg-white p-2 shadow-lg shadow-slate-900/5 sm:mt-8 sm:grid-cols-[2fr_1fr_1fr_auto]">
                    <label class="relative"><span class="sr-only">Search TV channels</span><input wire:model.live.debounce.300ms="q" autocomplete="off" placeholder="Search a TV channel" class="min-h-14 w-full rounded-[18px] border-0 bg-stone-100 px-4 pr-11 text-base outline-none"><span wire:loading wire:target="q" class="absolute right-4 top-1/2 size-4 -translate-y-1/2 animate-spin rounded-full border-2 border-cyan-600 border-r-transparent" aria-label="Searching"></span></label>
                    <select wire:model.live="country" class="min-h-14 rounded-[18px] border-0 bg-stone-100 px-4 font-bold"><option value="">Every country</option>@foreach($countries as $item)<option value="{{ $item->iso_alpha_2 }}">{{ $item->name }} ({{ $item->tv_count }})</option>@endforeach</select>
                    <select wire:model.live="sort" class="min-h-14 rounded-[18px] border-0 bg-stone-100 px-4 font-bold"><option value="recommended">Nigeria first</option><option value="name_asc">Name A–Z</option><option value="name_desc">Name Z–A</option><option value="country">Country A–Z</option></select>
                    <button class="rounded-[18px] bg-cyan-600 px-6 py-3 font-extrabold text-white" wire:loading.attr="disabled">Apply</button>
                </form>
            </div>

            <div class="mt-7"><div class="flex justify-between"><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-slate-500">Popular destinations</p><span class="text-[10px] font-semibold text-slate-400 sm:hidden">Scroll to explore</span><span class="hidden text-[10px] font-semibold text-slate-400 sm:inline">Select a country</span></div><div class="wavexa-rail -mx-4 mt-3 flex gap-2 overflow-x-auto px-4 pb-1 sm:mx-0 sm:grid sm:grid-cols-4 sm:overflow-visible sm:px-0 lg:grid-cols-5">@foreach($countries->sortByDesc('tv_count')->take(10) as $item)<button type="button" wire:click="$set('country', '{{ $item->iso_alpha_2 }}')" class="flex min-h-11 shrink-0 items-center justify-between gap-2 rounded-xl border px-3 text-left text-xs font-bold {{ $country === $item->iso_alpha_2 ? 'border-cyan-500 bg-cyan-100 text-cyan-950' : 'border-stone-300 bg-white text-slate-700 hover:border-cyan-400' }}"><span class="truncate">{{ $item->name }}</span><span class="rounded-lg bg-stone-100 px-2 py-1 text-[9px] text-slate-500">{{ $item->tv_count }}</span></button>@endforeach</div></div>
        </div>
    </section>

    @if($q === '' && $country === '' && $channels->currentPage() === 1)
        <section class="border-b border-stone-200 bg-white py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-end justify-between"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-violet-700">Just added</p><h2 class="mt-2 text-2xl font-extrabold">New to the directory</h2></div><span class="hidden text-xs text-slate-400 sm:block">Recently synchronized sources</span></div><div class="wavexa-rail -mx-4 mt-5 flex gap-3 overflow-x-auto px-4 pb-2 sm:mx-0 sm:grid sm:grid-cols-3 sm:px-0 lg:grid-cols-6">@foreach($recentChannels as $item)<a wire:navigate href="{{ route('tv.show', $item->slug) }}" class="w-[210px] shrink-0 border-l-2 border-violet-300 bg-stone-50 p-4 transition hover:border-violet-600 sm:w-auto"><span class="text-[9px] font-extrabold uppercase tracking-wider text-slate-400">{{ $item->country?->name ?? 'Global' }}</span><h3 class="mt-3 truncate text-sm font-extrabold">{{ $item->name }}</h3><p class="mt-2 text-[10px] text-slate-500">Open channel →</p></a>@endforeach</div></div></section>
    @endif

    <section id="channels" class="bg-stone-50 py-10 sm:py-14">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8" wire:loading.class="opacity-60">
            <div class="flex items-end justify-between"><div><p class="text-[11px] font-extrabold uppercase tracking-[.2em] text-cyan-700">On air</p><h2 class="mt-1 text-2xl font-extrabold sm:text-3xl">{{ $q !== '' ? 'Results for “'.$q.'”' : 'Choose a channel' }}</h2><p wire:loading wire:target="q" class="mt-1 text-xs font-semibold text-cyan-700">Searching channels…</p></div>@if($q !== '' || $country !== '' || $sort !== 'recommended')<button wire:click="clearFilters" class="rounded-full bg-stone-200 px-3 py-2 text-xs font-bold">Clear filters</button>@endif</div>
            @if($channels->isEmpty())
                <div class="mt-8 rounded-[28px] border border-dashed border-stone-300 bg-white p-10 text-center"><h3 class="text-xl font-extrabold">No channels found</h3><p class="mt-2 text-sm text-slate-500">Try another country or a broader channel name.</p></div>
            @else
                <div class="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    @foreach($channels as $channel)
                        @php($logo = $channel->artworks->firstWhere('is_primary', true)?->url) @php($meta = $channel->sources->first()?->metadata ?? [])
                        <article wire:key="channel-{{ $channel->id }}" class="overflow-hidden rounded-2xl border border-stone-200 bg-white transition hover:-translate-y-1 hover:border-cyan-300 hover:shadow-xl"><a wire:navigate href="{{ route('tv.show', $channel->slug) }}" class="block"><div class="relative aspect-video bg-slate-950"><span class="absolute inset-0 grid place-items-center text-5xl font-black text-cyan-300">{{ mb_strtoupper(mb_substr($channel->name, 0, 1)) }}</span>@if($logo)<img src="{{ $logo }}" alt="" class="absolute inset-0 size-full object-contain p-8" loading="lazy" onerror="this.remove()">@endif<div class="absolute inset-x-3 bottom-3 flex items-center justify-between"><span class="rounded-md bg-white px-2 py-1 text-[9px] font-extrabold tracking-wider">LIVE</span>@if($meta['is_geoblocked'] ?? false)<span class="rounded-md bg-amber-300 px-2 py-1 text-[9px] font-bold">LOCATION LIMITED</span>@endif</div></div><div class="flex items-center justify-between gap-3 p-4"><div class="min-w-0"><h3 class="truncate text-base font-extrabold">{{ $channel->name }}</h3><p class="mt-1 truncate text-xs text-slate-500">{{ $channel->country?->name ?? ($meta['group'] ?? 'Global') }}</p></div><span class="grid size-10 shrink-0 place-items-center rounded-full border border-stone-200 text-xs text-cyan-800">▶</span></div></a></article>
                    @endforeach
                </div>
                {{ $channels->onEachSide(1)->links('livewire.components.pagination', data: ['scrollTo' => '#channels']) }}
            @endif
        </div>
    </section>
</div>
