<div wire:poll.10s><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-orange-700">Sources & playback · Ingestion</p><h2 class="mt-2 text-3xl font-extrabold">{{ $type === 'tv' ? 'TV imports' : str($type)->headline().' imports' }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Queue a bounded background import from {{ $type === 'radio' ? 'Radio Browser' : ($type === 'tv' ? 'Free-TV' : 'the Apple Podcasts directory and publisher RSS feeds') }}.</p></div><a href="{{ route('admin.ingestion.history') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-stone-300 bg-white px-4 text-sm font-extrabold">Full history →</a></div>
@if(session('status'))<div class="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif @error('source')<div class="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-800">{{ $message }}</div>@enderror
<section class="mt-7 rounded-3xl border border-stone-200 bg-white p-5 sm:p-6"><h3 class="text-xl font-extrabold">Import options</h3><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
@if($type === 'podcast')<label class="text-xs font-bold text-slate-600 sm:col-span-2">Directory search term<input wire:model="term" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50" placeholder="Nigeria, technology, news"></label>@endif
<label class="text-xs font-bold text-slate-600">Country code {{ $type === 'podcast' ? '' : '(optional)' }}<input wire:model="country" maxlength="2" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50 uppercase" placeholder="NG"></label>
@if($type === 'radio')<label class="text-xs font-bold text-slate-600">Station name<input wire:model="name" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50"></label><label class="text-xs font-bold text-slate-600">Genre or tag<input wire:model="tag" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50"></label><label class="text-xs font-bold text-slate-600">Language<input wire:model="language" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50"></label><label class="text-xs font-bold text-slate-600">Offset<input type="number" min="0" wire:model="offset" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50"></label>@endif
<label class="text-xs font-bold text-slate-600">Maximum {{ $type === 'tv' ? 'entries' : 'items' }}<input type="number" min="1" wire:model="limit" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50"></label>@if($type === 'podcast')<label class="text-xs font-bold text-slate-600">Episodes per podcast<input type="number" min="1" max="100" wire:model="episodes" class="mt-2 min-h-12 w-full rounded-xl border-stone-300 bg-stone-50"></label>@endif
</div>@if($errors->any())<p class="mt-4 text-sm font-bold text-rose-700">Please correct the highlighted import options.</p>@endif<button wire:click="queueImport" wire:loading.attr="disabled" class="mt-6 min-h-12 rounded-xl bg-slate-950 px-6 text-sm font-extrabold text-white disabled:opacity-50"><span wire:loading.remove wire:target="queueImport">Queue import</span><span wire:loading wire:target="queueImport">Queuing…</span></button><p class="mt-3 text-xs leading-5 text-slate-500">Imports run through Laravel queues. Keep <code class="rounded bg-stone-100 px-1">php artisan queue:work</code> running.</p></section>
<section class="mt-6"><h3 class="text-xl font-extrabold">Recent runs</h3><div class="mt-4 grid gap-3">@forelse($runs as $run)<article class="flex flex-wrap items-center gap-3 rounded-2xl border border-stone-200 bg-white p-4"><span class="size-2 rounded-full {{ $run->status === 'completed' ? 'bg-emerald-500' : ($run->status === 'failed' ? 'bg-rose-500' : ($run->status === 'running' ? 'bg-amber-500 animate-pulse' : 'bg-slate-400')) }}"></span><div class="min-w-0 flex-1"><strong class="text-sm">Import #{{ $run->id }}</strong><p class="mt-1 truncate text-xs text-slate-500">{{ str($run->status)->headline() }} · {{ $run->requestedBy?->email ?? 'System' }} · {{ $run->created_at->diffForHumans() }}</p></div>@if($run->result)<div class="text-xs font-bold text-slate-600">@foreach($run->result as $label => $value)<span class="ml-2">{{ str($label)->headline() }}: {{ $value }}</span>@endforeach</div>@endif</article>@empty<p class="rounded-2xl border border-dashed border-stone-300 p-8 text-center text-sm text-slate-500">No {{ $type }} imports have been queued.</p>@endforelse</div></section></div>
