<?php

use App\Livewire\Admin\Dashboard;
use App\Livewire\Admin\Geography\Cities;
use App\Livewire\Admin\Geography\Countries;
use App\Livewire\Admin\Geography\Regions;
use App\Livewire\Admin\Podcasts\Episodes as PodcastEpisodes;
use App\Livewire\Admin\Podcasts\Feeds as PodcastFeeds;
use App\Livewire\Admin\Podcasts\Form as PodcastForm;
use App\Livewire\Admin\Podcasts\Index as PodcastIndex;
use App\Livewire\Admin\Radio\DataQuality as RadioDataQuality;
use App\Livewire\Admin\Radio\Duplicates as RadioDuplicates;
use App\Livewire\Admin\Radio\Form as RadioForm;
use App\Livewire\Admin\Radio\Index as RadioIndex;
use App\Livewire\Admin\Radio\Show as RadioShow;
use App\Livewire\Admin\StreamHealth;
use App\Livewire\Admin\Taxonomy\Assignments;
use App\Livewire\Admin\Taxonomy\TagCleanup;
use App\Livewire\Admin\Taxonomy\Terms;
use App\Livewire\Admin\Television\DataQuality as TelevisionDataQuality;
use App\Livewire\Admin\Television\Duplicates as TelevisionDuplicates;
use App\Livewire\Admin\Television\Form as TelevisionForm;
use App\Livewire\Admin\Television\Index as TelevisionIndex;
use App\Livewire\Admin\Television\Show as TelevisionShow;
use Illuminate\Support\Facades\Route;

Route::get('/', Dashboard::class)->name('dashboard');
Route::get('/stream-health', StreamHealth::class)->name('stream-health');
Route::get('/geography/countries', Countries::class)->name('geography.countries');
Route::get('/geography/regions', Regions::class)->name('geography.regions');
Route::get('/geography/cities', Cities::class)->name('geography.cities');
Route::get('/taxonomy/categories', Terms::class)->name('taxonomy.categories')->defaults('kind', 'categories');
Route::get('/taxonomy/genres', Terms::class)->name('taxonomy.genres')->defaults('kind', 'genres');
Route::get('/taxonomy/languages', Terms::class)->name('taxonomy.languages')->defaults('kind', 'languages');
Route::get('/taxonomy/tag-cleanup', TagCleanup::class)->name('taxonomy.tag-cleanup');
Route::get('/taxonomy/{kind}/{term}', Assignments::class)->name('taxonomy.assignments');
Route::get('/radio', RadioIndex::class)->name('radio.index');
Route::get('/radio/create', RadioForm::class)->name('radio.create');
Route::get('/radio/duplicates', RadioDuplicates::class)->name('radio.duplicates');
Route::get('/radio/data-quality', RadioDataQuality::class)->name('radio.data-quality');
Route::get('/radio/{station}/edit', RadioForm::class)->name('radio.edit');
Route::get('/radio/{station}', RadioShow::class)->name('radio.show');
Route::get('/television', TelevisionIndex::class)->name('television.index');
Route::get('/television/create', TelevisionForm::class)->name('television.create');
Route::get('/television/duplicates', TelevisionDuplicates::class)->name('television.duplicates');
Route::get('/television/data-quality', TelevisionDataQuality::class)->name('television.data-quality');
Route::get('/television/{channel}/edit', TelevisionForm::class)->name('television.edit');
Route::get('/television/{channel}', TelevisionShow::class)->name('television.show');
Route::get('/podcasts', PodcastIndex::class)->name('podcasts.index');
Route::get('/podcasts/create', PodcastForm::class)->name('podcasts.create');
Route::get('/podcasts/episodes', PodcastEpisodes::class)->name('podcasts.episodes');
Route::get('/podcasts/feeds', PodcastFeeds::class)->name('podcasts.feeds');
