<div>
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-fuchsia-700">Discovery · Editorial</p><h2 class="mt-2 text-3xl font-extrabold">{{ str($collection)->headline() }} media</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{{ $collection === 'featured' ? 'Choose the stories and live signals Wavexa should spotlight publicly.' : 'Blend editorial judgment with audience signals to shape what feels current.' }}</p></div><a href="{{ route('home') }}" target="_blank" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-950 px-4 text-sm font-extrabold text-white">Preview homepage ↗</a></div>
    @if(session('status'))<div class="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif

    <section class="mt-7 rounded-3xl border border-stone-200 bg-white p-5 sm:p-6"><div class="flex items-center justify-between"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-fuchsia-700">Live collection</p><h3 class="mt-1 text-xl font-extrabold">Publication order</h3></div><span class="rounded-full bg-fuchsia-50 px-3 py-1 text-xs font-bold text-fuchsia-800">{{ $placements->count() }} selected</span></div>
        <div class="mt-5 grid gap-3">@forelse($placements as $placement)<article class="flex flex-wrap items-center gap-3 rounded-2xl border border-stone-200 p-3"><span class="grid size-11 place-items-center rounded-xl bg-stone-100 text-sm font-black">{{ $placement->position }}</span><div class="min-w-0 flex-1"><strong class="block truncate">{{ $placement->media->name }}</strong><p class="mt-1 text-xs text-slate-500">{{ str($placement->media->type->value)->headline() }} · {{ $placement->media->country?->name ?? 'Worldwide' }} · @if($placement->starts_at && $placement->starts_at->isFuture())Scheduled {{ $placement->starts_at->diffForHumans() }}@elseif($placement->ends_at && $placement->ends_at->isPast())Expired@else<span class="font-bold text-emerald-700">Live now</span>@endif</p></div><div class="flex gap-2"><button wire:click="move({{ $placement->id }}, 'up')" class="grid size-10 place-items-center rounded-xl bg-stone-100" aria-label="Move up">↑</button><button wire:click="move({{ $placement->id }}, 'down')" class="grid size-10 place-items-center rounded-xl bg-stone-100" aria-label="Move down">↓</button><button wire:click="remove({{ $placement->id }})" wire:confirm="Remove this placement?" class="min-h-10 rounded-xl bg-rose-50 px-3 text-xs font-bold text-rose-700">Remove</button></div></article>@empty<p class="rounded-2xl border border-dashed border-stone-300 p-8 text-center text-sm text-slate-500">Nothing selected yet. Add published media below.</p>@endforelse</div>
    </section>

    <section class="mt-6 rounded-3xl border border-stone-200 bg-white p-5 sm:p-6"><h3 class="text-xl font-extrabold">Add to collection</h3><div class="mt-4 grid gap-3 lg:grid-cols-[1fr_180px]"><input wire:model.live.debounce.300ms="q" class="min-h-12 rounded-xl border-stone-300 bg-stone-50" placeholder="Search name or country"><select wire:model.live="type" class="min-h-12 rounded-xl border-stone-300 bg-stone-50"><option value="all">All media</option><option value="radio">Radio</option><option value="tv">Television</option><option value="podcast">Podcasts</option></select></div>
        <details class="mt-3 rounded-2xl bg-stone-50 p-4"><summary class="cursor-pointer text-sm font-extrabold">Optional schedule and editor note</summary><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-xs font-bold text-slate-600">Starts at<input type="datetime-local" wire:model="startsAt" class="mt-2 min-h-11 w-full rounded-xl border-stone-300 bg-white"></label><label class="text-xs font-bold text-slate-600">Ends at<input type="datetime-local" wire:model="endsAt" class="mt-2 min-h-11 w-full rounded-xl border-stone-300 bg-white"></label><label class="sm:col-span-2 text-xs font-bold text-slate-600">Internal note<input wire:model="note" maxlength="255" class="mt-2 min-h-11 w-full rounded-xl border-stone-300 bg-white" placeholder="Why this belongs here"></label></div>@error('endsAt')<p class="mt-2 text-xs font-bold text-rose-700">{{ $message }}</p>@enderror</details>
        <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@forelse($candidates as $item)<article class="flex items-center gap-3 rounded-2xl border border-stone-200 p-3"><span class="grid size-11 shrink-0 place-items-center rounded-xl bg-fuchsia-50 font-black text-fuchsia-700">{{ mb_strtoupper(mb_substr($item->name, 0, 1)) }}</span><div class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ $item->name }}</strong><small class="text-slate-500">{{ str($item->type->value)->headline() }} · {{ $item->country?->name ?? 'Worldwide' }}</small></div><button wire:click="add({{ $item->id }})" class="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-950 font-bold text-white" aria-label="Add {{ $item->name }}">+</button></article>@empty<p class="col-span-full p-8 text-center text-sm text-slate-500">No matching published media.</p>@endforelse</div><div class="mt-5">{{ $candidates->links('livewire.components.pagination', data: ['scrollTo' => 'main']) }}</div>
    </section>
</div>
