<div class="mx-auto max-w-3xl">
    <div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-700">Podcast ingestion</p><h2 class="mt-2 text-3xl font-extrabold">Add a podcast from RSS</h2><p class="mt-2 text-sm leading-6 text-slate-500">Enter the publisher's public RSS feed. Wavexa will import show metadata and recent playable episodes without copying their media files.</p></div>
    <form wire:submit="save" class="mt-7 space-y-5 rounded-3xl border border-stone-200 bg-white p-5 sm:p-7">
        <label class="block"><span class="text-sm font-bold">Public RSS feed URL</span><input wire:model="feedUrl" type="url" class="mt-2 min-h-12 w-full rounded-xl border border-stone-300 px-4" placeholder="https://publisher.example/show/feed.xml">@error('feedUrl')<span class="mt-2 block text-sm font-bold text-rose-700">{{ $message }}</span>@enderror</label>
        <div class="grid gap-5 sm:grid-cols-2"><label><span class="text-sm font-bold">Country</span><select wire:model="country" class="mt-2 min-h-12 w-full rounded-xl border border-stone-300 px-3">@foreach($countries as $item)<option value="{{ $item->iso_alpha_2 }}">{{ $item->name }}</option>@endforeach</select>@error('country')<span class="text-sm text-rose-700">{{ $message }}</span>@enderror</label><label><span class="text-sm font-bold">Recent episodes to import</span><input wire:model="episodeLimit" type="number" min="1" max="100" class="mt-2 min-h-12 w-full rounded-xl border border-stone-300 px-4">@error('episodeLimit')<span class="text-sm text-rose-700">{{ $message }}</span>@enderror</label></div>
        <div class="rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Rights-aware ingestion:</strong> only add feeds intended for public podcast distribution. Private, authenticated, or paid feeds should not be entered.</div>
        <div class="flex flex-col gap-3 sm:flex-row sm:justify-end"><a wire:navigate href="{{ route('admin.podcasts.index') }}" class="grid min-h-12 place-items-center rounded-xl border border-stone-300 px-5 text-sm font-bold">Cancel</a><button class="min-h-12 rounded-xl bg-amber-600 px-6 text-sm font-extrabold text-white" wire:loading.attr="disabled"><span wire:loading.remove>Import podcast</span><span wire:loading>Reading publisher feed…</span></button></div>
    </form>
</div>
