<div>
    <div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-orange-600">Audience · Access</p><h2 class="mt-2 text-3xl font-extrabold">All users</h2><p class="mt-2 text-sm text-slate-500">Review registered accounts and appoint trusted administrators. Administrators receive full dashboard access.</p></div>
    @if(session('status'))<div class="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
    @error('role')<div class="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-800">{{ $message }}</div>@enderror
    <div class="mt-6 grid gap-3 rounded-2xl border border-stone-200 bg-white p-3 sm:grid-cols-[1fr_190px]"><input wire:model.live.debounce.300ms="q" type="search" class="min-h-12 rounded-xl border-0 bg-stone-100 px-4" placeholder="Search name or email"><select wire:model.live="role" class="min-h-12 rounded-xl border-0 bg-stone-100 px-4 font-bold"><option value="all">All users</option><option value="admins">Administrators</option><option value="listeners">Listeners</option></select></div>
    <div class="mt-5 overflow-hidden rounded-2xl border border-stone-200 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-stone-100 text-[9px] font-extrabold uppercase tracking-wider text-slate-500"><tr><th class="p-4">User</th><th class="p-4">Role</th><th class="p-4">Library activity</th><th class="p-4">Joined</th><th class="p-4 text-right">Access</th></tr></thead><tbody class="divide-y divide-stone-100">
        @forelse($users as $user)<tr wire:key="user-{{ $user->id }}"><td class="p-4"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-orange-100 font-black text-orange-800">{{ mb_strtoupper(mb_substr($user->name, 0, 1)) }}</span><span><strong class="block">{{ $user->name }} @if($user->is(auth()->user()))<small class="text-slate-400">(you)</small>@endif</strong><small class="text-slate-500">{{ $user->email }}</small></span></div></td><td class="p-4"><span class="rounded-full px-3 py-1.5 text-xs font-extrabold {{ $user->is_admin ? 'bg-violet-100 text-violet-800' : 'bg-stone-100 text-slate-600' }}">{{ $user->is_admin ? 'Administrator' : 'Listener' }}</span></td><td class="p-4 text-xs text-slate-500">{{ number_format($user->favorite_media_count) }} saved · {{ number_format($user->playback_history_count) }} played</td><td class="p-4 text-xs text-slate-500">{{ $user->created_at->format('M j, Y') }}</td><td class="p-4 text-right">@if($user->is_admin)<button wire:click="setAdmin({{ $user->id }}, false)" wire:confirm="Remove administrator access from {{ addslashes($user->name) }}?" @disabled($user->is(auth()->user())) class="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700 disabled:cursor-not-allowed disabled:opacity-40">Remove admin</button>@else<button wire:click="setAdmin({{ $user->id }}, true)" wire:confirm="Give {{ addslashes($user->name) }} full dashboard access?" class="rounded-xl bg-slate-950 px-3 py-2 text-xs font-bold text-white">Appoint admin</button>@endif</td></tr>
        @empty<tr><td colspan="5" class="p-12 text-center font-bold text-slate-500">No users match these filters.</td></tr>@endforelse
    </tbody></table></div></div><div class="mt-5">{{ $users->links('livewire.components.pagination', data: ['scrollTo' => 'main']) }}</div>
</div>
