<div>
    <div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-blue-700">Discovery · Search</p><h2 class="mt-2 text-3xl font-extrabold">{{ $kind === 'index' ? 'Search index' : ($kind === 'popular' ? 'Popular searches' : 'No-result searches') }}</h2><p class="mt-2 text-sm text-slate-500">{{ $kind === 'index' ? 'Monitor searchable catalogue coverage and user search health.' : ($kind === 'popular' ? 'Understand what audiences successfully discover.' : 'Find catalogue gaps and spelling patterns that return nothing.') }}</p></div>
    <div class="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach($stats as $label => $value)<article class="rounded-2xl border border-stone-200 bg-white p-4"><p class="text-[9px] font-extrabold uppercase tracking-wider text-slate-400">{{ str($label)->headline() }}</p><p class="mt-2 text-3xl font-extrabold">{{ number_format($value) }}</p></article>@endforeach</div>
    @if($kind === 'index')
        <section class="mt-6 rounded-3xl border border-stone-200 bg-white p-5"><h3 class="text-xl font-extrabold">Searchable catalogue</h3><div class="mt-5 grid gap-3 sm:grid-cols-3">@foreach(['radio' => 'Radio stations', 'tv' => 'TV channels', 'podcast' => 'Podcasts'] as $value => $label)<div class="rounded-2xl bg-blue-50 p-5"><small class="font-extrabold uppercase text-blue-700">{{ $label }}</small><strong class="mt-2 block text-3xl">{{ number_format($mediaCounts[$value] ?? 0) }}</strong></div>@endforeach</div><div class="mt-5 rounded-2xl bg-stone-100 p-4 text-sm leading-6 text-slate-600"><strong>Current engine:</strong> database-backed search across media names, descriptions, countries, genres, and languages. Results update as users type; analytics begin at two characters.</div><a href="{{ route('search') }}" target="_blank" class="mt-5 inline-flex rounded-xl bg-blue-700 px-5 py-3 text-sm font-extrabold text-white">Open public search ↗</a></section>
    @else
        <label class="mt-6 block rounded-2xl border border-stone-200 bg-white p-2"><input wire:model.live.debounce.300ms="q" class="min-h-12 w-full rounded-xl border-0 bg-stone-100 px-4" placeholder="Filter search terms"></label>
        <div class="mt-5 overflow-hidden rounded-2xl border border-stone-200 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-stone-100 text-[9px] font-extrabold uppercase tracking-wider text-slate-500"><tr><th class="p-4">Search term</th><th class="p-4">Searches</th><th class="p-4">Average results</th><th class="p-4">Last searched</th><th class="p-4"></th></tr></thead><tbody class="divide-y divide-stone-100">@forelse($searches as $item)<tr><td class="p-4 font-extrabold">{{ $item->display_query }}</td><td class="p-4">{{ number_format($item->searches) }}</td><td class="p-4">{{ number_format($item->average_results) }}</td><td class="p-4 text-xs text-slate-500">{{ now()->parse($item->last_searched_at)->diffForHumans() }}</td><td class="p-4 text-right"><a href="{{ route('search', ['q' => $item->display_query]) }}" target="_blank" class="rounded-lg bg-blue-100 px-3 py-2 text-xs font-bold text-blue-800">Inspect ↗</a></td></tr>@empty<tr><td colspan="5" class="p-12 text-center font-bold">No search data yet.</td></tr>@endforelse</tbody></table></div></div><div class="mt-6">{{ $searches->links('livewire.components.pagination', data: ['scrollTo' => 'main']) }}</div>
    @endif
</div>
