@extends('layouts.app')
@section('title', 'Live Radio Around the World — Wavexa')
@section('description', 'Browse and listen to directory-listed live radio stations by country, genre, and language on Wavexa.')
@section('content')
<section class="border-b border-orange-200 bg-orange-50"><div class="mx-auto max-w-7xl px-4 pb-8 pt-7 sm:px-6 sm:py-14 lg:px-8">
    <div class="flex items-center justify-between"><span class="inline-flex items-center gap-2 rounded-full border border-orange-200 bg-white px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-orange-700"><span class="size-2 rounded-full bg-emerald-500"></span>Live worldwide</span><a wire:navigate href="#stations" class="text-xs font-bold text-slate-500">Browse stations ↓</a></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-[1fr_360px] lg:items-end"><div><h1 class="max-w-3xl text-[42px] font-extrabold leading-[0.95] tracking-[-0.055em] sm:text-6xl">Hear what the world is listening to.</h1><p class="mt-4 max-w-xl text-[15px] leading-7 text-slate-600 sm:text-base">Local voices, live music, breaking news, and culture—streamed directly from stations around the globe.</p></div><div class="grid grid-cols-2 gap-3"><div class="rounded-[22px] bg-slate-950 p-4 text-white"><strong class="block text-3xl tracking-tight">{{ number_format($stations->total()) }}</strong><span class="mt-1 block text-[11px] text-slate-400">live stations</span></div><div class="rounded-[22px] border border-orange-200 bg-white p-4"><strong class="block text-3xl tracking-tight">{{ $countries->count() }}</strong><span class="mt-1 block text-[11px] text-slate-500">countries</span></div></div></div>
    <button type="button" data-filter-toggle aria-expanded="false" class="mt-6 flex w-full items-center justify-between rounded-[20px] bg-white px-4 py-4 text-sm font-extrabold shadow-sm ring-1 ring-orange-200 sm:hidden"><span class="flex items-center gap-2"><svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M7 12h10M10 18h4"/></svg>Search and filters</span><span>＋</span></button>
    <form data-filter-panel method="GET" action="{{ route('radio.index') }}" class="mt-3 hidden gap-3 rounded-[26px] border border-orange-200 bg-white p-3 shadow-xl shadow-orange-950/5 sm:mt-7 sm:grid sm:grid-cols-2 lg:grid-cols-4">
        <label class="flex min-h-14 items-center gap-3 rounded-[18px] bg-stone-100 px-4 sm:col-span-2"><svg viewBox="0 0 24 24" class="size-5 shrink-0 text-slate-400" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><span class="sr-only">Search</span><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Station, city, or region" class="w-full bg-transparent text-base outline-none"></label>
        @foreach ([['country','Every country',$countries->map(fn($x)=>[$x->iso_alpha_2,$x->name])],['sort','Most popular',collect([['popular','Most popular'],['location','Location A–Z'],['name_asc','Name A–Z'],['name_desc','Name Z–A'],['bitrate','Highest bitrate'],['recent','Recently checked']])]] as [$name,$empty,$options])<label class="min-w-0"><span class="sr-only">{{ $empty }}</span><select name="{{ $name }}" class="min-h-14 w-full rounded-[18px] border-0 bg-stone-100 px-4 text-base font-bold outline-none">@if($name==='country')<option value="">{{ $empty }}</option>@endif @foreach($options as $option)<option value="{{ $option[0] }}" @selected(($name==='sort' ? $sort : ($filters[$name] ?? ''))===$option[0])>{{ $option[1] }}</option>@endforeach</select></label>@endforeach
        <div class="grid gap-3 sm:col-span-2 sm:grid-cols-2 lg:col-span-4 lg:grid-cols-5">
            <select name="state" class="min-h-13 rounded-[17px] border border-stone-200 bg-white px-3 text-sm font-bold"><option value="">All regions</option>@foreach($states as $state)<option @selected(($filters['state']??'')===$state)>{{ $state }}</option>@endforeach</select>
            <select name="genre" class="min-h-13 rounded-[17px] border border-stone-200 bg-white px-3 text-sm font-bold"><option value="">All genres</option>@foreach($genres as $genre)<option value="{{ $genre->slug }}" @selected(($filters['genre']??'')===$genre->slug)>{{ $genre->name }} · {{ $genre->radio_count }}</option>@endforeach</select>
            <select name="language" class="min-h-13 rounded-[17px] border border-stone-200 bg-white px-3 text-sm font-bold"><option value="">All languages</option>@foreach($languages as $language)<option value="{{ $language->id }}" @selected((string)($filters['language']??'')===(string)$language->id)>{{ $language->name }}</option>@endforeach</select>
            <select name="codec" class="min-h-13 rounded-[17px] border border-stone-200 bg-white px-3 text-sm font-bold"><option value="">All formats</option>@foreach($codecs as $codec)<option @selected(($filters['codec']??'')===$codec)>{{ $codec }}</option>@endforeach</select>
            <button class="min-h-13 rounded-[17px] bg-orange-500 px-5 font-extrabold text-white">Show results</button>
        </div>
    </form>
    <div class="mt-6"><div class="flex items-center justify-between"><p class="text-[11px] font-extrabold uppercase tracking-[0.18em] text-slate-500">Popular destinations</p><span class="text-[11px] text-slate-400">Swipe</span></div><div class="wavexa-rail -mx-4 mt-3 flex gap-2 overflow-x-auto px-4 pb-1 sm:mx-0 sm:px-0">@foreach($countries->sortByDesc('radio_count')->take(20) as $country)<a wire:navigate href="{{ route('countries.show',$country->iso_alpha_2) }}" class="flex shrink-0 items-center gap-2 rounded-full border border-orange-200 bg-white py-2 pl-3 pr-2 text-xs font-bold text-slate-700"><span>{{ $country->name }}</span><span class="rounded-full bg-orange-100 px-2 py-1 text-[10px] text-orange-800">{{ $country->radio_count }}</span></a>@endforeach</div></div>
</div></section>

@if(!request()->hasAny(['q','country','state','genre','language','codec']))<section class="border-b border-stone-200 bg-white py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-end justify-between"><div><p class="text-[11px] font-extrabold uppercase tracking-[0.2em] text-rose-600">Moving now</p><h2 class="mt-1 text-2xl font-extrabold tracking-tight">Trending on Wavexa</h2></div><span class="text-xs text-slate-400">Live momentum</span></div><div class="wavexa-rail -mx-4 mt-5 flex snap-x gap-3 overflow-x-auto px-4 pb-2 sm:mx-0 sm:px-0">@foreach($trendingStations as $item)<a wire:navigate href="{{ route('radio.show',$item->slug) }}" class="w-[245px] shrink-0 snap-start rounded-[24px] bg-rose-50 p-5"><span class="grid size-10 place-items-center rounded-2xl bg-rose-500 font-black text-white">{{ mb_strtoupper(mb_substr(ltrim($item->name,'#'),0,1)) }}</span><h3 class="mt-6 truncate text-base font-extrabold">{{ $item->name }}</h3><p class="mt-1 text-xs text-slate-500">{{ $item->country?->name ?? 'Global' }} · {{ number_format($item->radioStation?->source_click_trend ?? 0) }} trending</p></a>@endforeach</div></div></section>@endif

<section id="stations" class="py-10 sm:py-14"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-end justify-between gap-4"><div><p class="text-[11px] font-extrabold uppercase tracking-[0.2em] text-orange-600">Live directory</p><h2 class="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Pick a station</h2></div>@if(request()->hasAny(['q','country','state','genre','language','codec','sort']))<a wire:navigate href="{{ route('radio.index') }}" class="rounded-full bg-stone-200 px-3 py-2 text-xs font-bold">Clear filters</a>@endif</div>
@if($stations->isEmpty())<div class="mt-8 rounded-[28px] border border-dashed border-stone-300 bg-white p-10 text-center"><h3 class="text-xl font-extrabold">Nothing matches yet</h3><p class="mt-2 text-slate-500">Try a broader place or category.</p></div>@else<div class="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($stations as $station)@php($stream=$station->primaryStream)@php($source=$station->sources->first(fn($x)=>$x->sourceProvider?->slug==='radio-browser'))@php($art=$station->artworks->firstWhere('is_primary',true)?->url)@php($initial=mb_strtoupper(mb_substr(ltrim($station->name,'#'),0,1)))@php($streams=$station->streamSources->map(fn($x)=>['id'=>$x->id,'url'=>$x->resolved_url?:$x->url,'format'=>$x->format])->values())<article class="group rounded-[26px] border border-stone-200 bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div class="flex gap-4"><div class="relative grid size-20 shrink-0 place-items-center overflow-hidden rounded-[22px] bg-orange-100 text-2xl font-black text-orange-700">{{ $initial }}@if($art)<img src="{{ $art }}" alt="" class="absolute inset-0 size-full object-contain" loading="lazy" onerror="this.remove()">@endif</div><div class="min-w-0 flex-1"><div class="flex items-center gap-2"><span class="size-2 rounded-full bg-emerald-500"></span><span class="text-[10px] font-extrabold uppercase tracking-wider text-emerald-700">Live</span><span class="rounded-full bg-stone-100 px-2 py-1 text-[10px] font-bold text-slate-500">{{ $stream?->codec ?? 'Stream' }}</span></div><h3 class="mt-2 truncate text-lg font-extrabold">{{ $station->name }}</h3><p class="mt-1 truncate text-xs text-slate-500">{{ $station->country?->name ?? ($source?->metadata['country'] ?? 'Global') }}@if($station->radioStation?->source_state) · {{ $station->radioStation->source_state }}@endif</p></div></div><div class="mt-4 flex gap-2"><button data-play-station data-stream="{{ $stream?->resolved_url ?: $stream?->url }}" data-streams="{{ $streams->toJson() }}" data-title="{{ $station->name }}" data-slug="{{ $station->slug }}" data-art="{{ $initial }}" class="flex min-h-12 flex-1 items-center justify-center gap-2 rounded-[17px] bg-slate-950 text-sm font-extrabold text-white"><svg viewBox="0 0 24 24" class="size-4" fill="currentColor"><path d="m8 5 11 7-11 7Z"/></svg>Play live</button><a wire:navigate href="{{ route('radio.show',$station->slug) }}" class="grid size-12 place-items-center rounded-[17px] bg-stone-100" aria-label="Details">→</a></div></article>@endforeach</div>{{ $stations->onEachSide(1)->links('components.pagination-links') }}@endif</div></section>
@endsection
