@extends('layouts.app')

@section('title', $channel->name.' Live — Wavexa')
@section('description', 'Watch '.$channel->name.' live and view its source and availability details on Wavexa.')
@section('canonical', route('tv.show', $channel->slug))
@section('meta_image', $channel->artworks->firstWhere('is_primary', true)?->url ?? '')
@section('structured_data', \App\Support\Seo::schema($channel->name.' Live — Wavexa', 'Watch '.$channel->name.' live and view its source and availability details on Wavexa.', route('tv.show', $channel->slug), [['name' => 'Home', 'url' => route('home')], ['name' => 'TV', 'url' => route('tv.index')], ['name' => $channel->name, 'url' => route('tv.show', $channel->slug)]]))

@section('content')
    @php($stream = $channel->primaryStream)
    @php($source = $channel->sources->first())
    @php($metadata = $source?->metadata ?? [])
    <section class="bg-slate-950 text-white"><div class="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-10 lg:px-8">
        <nav aria-label="Breadcrumb"><ol class="flex flex-wrap items-center gap-2 text-sm font-bold text-cyan-300"><li><a wire:navigate href="{{ route('home') }}">Home</a></li><li aria-hidden="true">/</li><li><a wire:navigate href="{{ route('tv.index') }}">TV</a></li><li aria-hidden="true">/</li><li aria-current="page" class="truncate text-white">{{ $channel->name }}</li></ol></nav>
        <div data-tv-inline-host data-channel="{{ $channel->slug }}" class="mt-5 overflow-hidden rounded-[24px] border border-white/10 bg-black shadow-2xl">
            <div class="relative grid aspect-video place-items-center overflow-hidden bg-slate-900">@php($logo = $channel->artworks->firstWhere('is_primary', true)?->url)@if($logo)<img src="{{ $logo }}" alt="{{ $channel->name }} logo" class="absolute inset-0 size-full object-contain p-12 opacity-50" referrerpolicy="no-referrer">@endif<div class="absolute inset-0 bg-slate-950/45"></div><button type="button" data-play-tv data-autoplay data-slug="{{ $channel->slug }}" data-title="{{ $channel->name }}" data-stream="{{ $stream->resolved_url ?: $stream->url }}" data-streams="{{ $channel->streamSources->where('status', '!=', \App\Enums\StreamStatus::Offline)->map(fn ($item) => ['id' => $item->id, 'url' => $item->resolved_url ?: $item->url, 'format' => $item->format])->values()->toJson() }}" class="relative inline-flex items-center gap-3 rounded-2xl bg-white px-6 py-4 font-extrabold text-slate-950 shadow-xl"><span class="grid size-9 place-items-center rounded-full bg-cyan-500"><svg viewBox="0 0 24 24" class="ml-0.5 size-5" fill="currentColor"><path d="m8 5 11 7-11 7Z"/></svg></span>Watch live</button></div>
        </div>
        <div class="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-extrabold uppercase tracking-[0.18em] text-cyan-300">{{ $channel->country?->name ?? ($metadata['group'] ?? 'Global') }}</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight sm:text-5xl">{{ $channel->name }}</h1></div><span class="self-start rounded-full bg-amber-100 px-3 py-2 text-xs font-bold text-amber-900">Rights review pending</span></div>
        <div class="mt-4"><x-favorite-button :media="$channel" /></div>
    </div></section>
    <section class="py-10"><div class="mx-auto grid max-w-6xl gap-5 px-4 sm:px-6 lg:grid-cols-[1fr_320px] lg:px-8"><div class="rounded-[26px] border border-stone-200 bg-white p-6"><h2 class="text-xl font-extrabold">About this channel</h2><p class="mt-3 leading-7 text-slate-600">{{ $channel->description }}</p>@if ($metadata['is_geoblocked'] ?? false)<div class="mt-5 rounded-2xl bg-amber-100 p-4 text-sm font-semibold text-amber-950">This source is marked as geographically restricted and may not play in your current location.</div>@endif<button type="button" data-report-stream="{{ $stream->id }}" class="mt-5 text-sm font-bold text-rose-700 underline">Report broken stream</button><p data-report-message class="mt-2 hidden text-sm text-emerald-700"></p></div><aside class="rounded-[26px] border border-cyan-200 bg-cyan-50 p-6"><h2 class="font-extrabold">Source transparency</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-slate-500">Directory</dt><dd class="font-bold">Free-TV</dd></div><div><dt class="text-slate-500">Format</dt><dd class="font-bold uppercase">{{ $stream->format }}</dd></div><div><dt class="text-slate-500">Channel ID</dt><dd class="break-all font-bold">{{ $channel->tvChannel?->call_sign }}</dd></div></dl></aside></div></section>
@endsection
